#!/bin/sh

if [ "$AMPLIFY" == true ] ; then
    exec python2.7 /usr/bin/nginx-amplify-agent.py start \
                    --config=/etc/amplify-agent/agent.conf \
                    --pid=/var/run/amplify-agent/amplify-agent.pid \
                    --foreground
fi
